services:
  quiz_web:
    build:
      context: ./
    restart: on-failure
    networks:
      - quiz_web_network
    env_file:
      - envs/web.env
    ports:
      - "3000:3000"


networks:
  quiz_web_network: