# Generated by Django 4.1.7 on 2023-04-01 11:55

import django.contrib.auth.validators
from django.db import migrations, models
import helpers.validators.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    helpers.validators.validators.validate_profanity,
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
            ),
        ),
    ]
