services:
    web:
        build:
            context: ../
            dockerfile: ./bank/Dockerfile
            target: development
        restart: on-failure
        working_dir: /app
        networks:
            - web_network
        ports:
            - "6006:6006"
        volumes:
            - ./:/app/bank/
            - ../.eslintignore:/app/.eslintignore
            - ../.eslintrc.json:/app/.eslintrc.json
            - ../.prettierrc.json:/app/.prettierrc.json
            - ../package.json:/app/package.json
            - ../package-lock.json:/app/package-lock.json
            - ../tsconfig.json:/app/tsconfig.json
        env_file:
            - envs/web.env
        command: npm run -w bank storybook
        stdin_open: true
        tty: true

volumes:
    node_modules:

networks:
    web_network:
        driver: bridge
