services:
  backend_quiz:
    build:
        context: ./backend
        dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.envs/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
