services:
  proxy:
    build:
      context: ./nginx
    ports:
      - 8081:80
    depends_on:
      - backend_quiz
    networks:
      - backend_network
    volumes:
      - static_volume:/app/staticfiles

  backend_quiz:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.envs/.env
      - ./.envs/.env_db
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    depends_on:
      - backend_db
    networks:
      - backend_network
      - backend_db_network
    volumes:
      - static_volume:/app/staticfiles

  backend_db:
    image: postgres:15.1
    volumes:
      - backend_db_volume:/var/lib/postgres/data/
    env_file:
      - ./.envs/.env_db
    networks:
      - backend_db_network

volumes:
  backend_db_volume:
  static_volume:

networks:
  backend_db_network:
    driver: bridge
  backend_network:
    driver: bridge
