services:
  web:
    build:
      context: ./web
    restart: on-failure
    networks:
      - proxy-web
    env_file:
      - envs/web.env

  proxy:
    build:
      context: ./proxy
    restart: on-failure
    networks:
      - proxy-web
      - backend_network
    depends_on:
      - web
      - backend_quiz
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles

  backend_quiz:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.envs/.env
      - envs/.db.env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    depends_on:
      - backend_quiz_db
    networks:
      - backend_network
      - backend_quiz_db_network
    volumes:
      - static_volume:/app/staticfiles

  backend_quiz_db:
    image: postgres:15.1
    volumes:
      - backend_quiz_db_volume:/var/lib/postgresql/data
    env_file:
      - envs/.db.env
    networks:
      - backend_quiz_db_network

volumes:
  backend_quiz_db_volume:
  static_volume:

networks:
  backend_quiz_db_network:
    driver: bridge
  backend_network:
    driver: bridge
  proxy-web:
    driver: bridge
