services:
  backend_quiz:
    build:
        context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.envs/.env
      - ./.envs/.env_db
    ports:
      - 8000:8000
    depends_on:
      - backend_db
    restart: on-failure
    volumes:
      - ./backend:/app
    networks:
      - backend_network
      - backend_db_network

  backend_db:
    image: postgres:15.1
    volumes:
      - backend_db_volume:/var/lib/postgres/data/
    env_file:
      - .envs/.env_db
    ports:
      - 5432:5432
    networks:
      - backend_db_network

volumes:
  backend_db_volume:

networks:
  backend_db_network:
    driver: bridge
  backend_network:
    driver: bridge
