services:
  quiz_web:
    build:
      context: ./web
    restart: on-failure
    networks:
      - quiz_web_network
    env_file:
      - envs/web.env

  proxy:
    build:
      context: ./proxy
    restart: on-failure
    networks:
      - quiz_web_network
      - quiz_backend_network
    depends_on:
      - quiz_web
      - quiz_backend
    ports:
      - "80:80"
    volumes:
      - quiz_static_volume:/app/staticfiles

  quiz_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.envs/.env
      - envs/.db.env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    depends_on:
      - quiz_postgres
    networks:
      - quiz_backend_network
      - quiz_postgres_network
    volumes:
      - quiz_static_volume:/app/staticfiles

  quiz_postgres:
    image: postgres:15.1
    volumes:
      - quiz_postgres_volume:/var/lib/postgresql/data
    env_file:
      - envs/.db.env
    networks:
      - quiz_postgres_network

volumes:
  quiz_postgres_volume:
  quiz_static_volume:

networks:
  quiz_postgres_network:
    driver: bridge
  quiz_backend_network:
    driver: bridge
  quiz_web_network:
    driver: bridge
