version: "3"
services:
  web:
    container_name: quiz_web
    build:
      context: ./web
    restart: on-failure
    networks:
      - proxy-web

  proxy:
    container_name: quiz_proxy
    build:
      context: ./proxy
    restart: on-failure
    networks:
      - proxy-web
    depends_on:
      - web
    ports:
      - "80:80"

networks:
  proxy-web:
    driver: bridge
