# Generated by Django 4.1.7 on 2023-04-01 11:55

from django.db import migrations, models
import helpers.validators.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nick",
                    models.CharField(
                        max_length=30,
                        validators=[helpers.validators.validators.validate_profanity],
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, help_text="Calculated with Elo system."
                    ),
                ),
                (
                    "is_bot",
                    models.BooleanField(
                        default=False,
                        help_text="True if player is not real.",
                        verbose_name="Player type.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if player is an active player.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
    ]
