# Generated by Django 4.1.7 on 2023-04-16 02:34

from django.db import migrations, models
import django.db.models.deletion
import helpers.validators.validators


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        upload_to="players_avatars/",
                        validators=[
                            helpers.validators.validators.validate_avatar_file_type_and_dimensions
                        ],
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Points earned by player."
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Information whether player is online or not.",
                    ),
                ),
                (
                    "is_push_notification",
                    models.BooleanField(
                        default=False,
                        help_text="Information about whether player wants to receive push notifications.",
                    ),
                ),
                (
                    "is_findable",
                    models.BooleanField(
                        default=False,
                        help_text="Information about whether player wants to be visible in searches.",
                    ),
                ),
                (
                    "is_invitable",
                    models.BooleanField(
                        default=False,
                        help_text="Information whether player wants to be invited by other players.",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile",
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
