services:
  proxy:
    build:
      context: ./proxy
    restart: on-failure
    networks:
      - interview_backend_network
      - interview_web_network
    depends_on:
      - web
      - backend
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles

  web:
    build:
      context: web
      target: development
    restart: on-failure
    working_dir: /app
    networks:
      - interview_web_network
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    env_file:
      - envs/web.env
    command: npm run dev
    stdin_open: true
    tty: true


  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./envs/backend.env
      - ./envs/postgres.env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - interview_backend_network
      - interview_postgres_network
    volumes:
      - static_volume:/app/staticfiles

  postgres:
    image: postgres:15.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - envs/postgres.env
    networks:
      - interview_postgres_network

volumes:
  postgres_volume:
  static_volume:

networks:
  interview_postgres_network:
    driver: bridge
  interview_backend_network:
    driver: bridge
  interview_web_network:
    driver: bridge