# Generated by Django 4.1.7 on 2023-04-16 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    replaces = [
        ("players", "0001_initial"),
        ("players", "0002_alter_player_expiration_time"),
        ("players", "0003_alter_player_expiration_time_alter_player_start_time"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("duration", models.DurationField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nick", models.CharField(max_length=30)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, help_text="Indicates if player is active.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="players.accounttype"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
    ]
