# Generated by Django 4.1.7 on 2023-04-12 08:54

from django.db import migrations, models
import helpers.validators.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(max_length=300)),
                (
                    "owned_by_user_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Percentage of all users/players owning given badge.",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="How many points is given badge worth."
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="badges/",
                        validators=[
                            helpers.validators.validators.validate_badge_file_type
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
