# Generated by Django 4.1.7 on 2023-04-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreements",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("checkbox_1", models.BooleanField(default=False)),
                ("checkbox_2", models.BooleanField(default=False)),
                ("checkbox_3", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "agreement",
                "verbose_name_plural": "agreements",
            },
        ),
    ]
